// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package events

type Payload = byte
const (
	PayloadNONE Payload = 0
	PayloadCandidateTable Payload = 1
	PayloadStringPayload Payload = 2
)

var EnumNamesPayload = map[Payload]string{
	PayloadNONE:"NONE",
	PayloadCandidateTable:"CandidateTable",
	PayloadStringPayload:"StringPayload",
}

