// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package events

type Target = int8
const (
	TargetSubscriber Target = 0
	TargetPublisher Target = 1
)

var EnumNamesTarget = map[Target]string{
	TargetSubscriber:"Subscriber",
	TargetPublisher:"Publisher",
}

