// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package events

type Target = int8
const (
	TargetPublisher Target = 0
	TargetSubscriber Target = 1
)

var EnumNamesTarget = map[Target]string{
	TargetPublisher:"Publisher",
	TargetSubscriber:"Subscriber",
}

