// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package events

type Type = int8
const (
	TypeOffer Type = 0
	TypeAnswer Type = 1
	TypeSignal Type = 2
	TypeJoin Type = 3
)

var EnumNamesType = map[Type]string{
	TypeOffer:"Offer",
	TypeAnswer:"Answer",
	TypeSignal:"Signal",
	TypeJoin:"Join",
}

