// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package events

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type JoinPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsJoinPayload(buf []byte, offset flatbuffers.UOffsetT) *JoinPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &JoinPayload{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsJoinPayload(buf []byte, offset flatbuffers.UOffsetT) *JoinPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &JoinPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *JoinPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *JoinPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *JoinPayload) Offer() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *JoinPayload) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func JoinPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func JoinPayloadAddOffer(builder *flatbuffers.Builder, offer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(offer), 0)
}
func JoinPayloadAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(token), 0)
}
func JoinPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
