// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package events

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LatencyPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsLatencyPayload(buf []byte, offset flatbuffers.UOffsetT) *LatencyPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LatencyPayload{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsLatencyPayload(buf []byte, offset flatbuffers.UOffsetT) *LatencyPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LatencyPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *LatencyPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LatencyPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LatencyPayload) Timestamp() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *LatencyPayload) MutateTimestamp(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func (rcv *LatencyPayload) Id() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LatencyPayload) MutateId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func LatencyPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func LatencyPayloadAddTimestamp(builder *flatbuffers.Builder, timestamp float64) {
	builder.PrependFloat64Slot(0, timestamp, 0.0)
}
func LatencyPayloadAddId(builder *flatbuffers.Builder, id uint16) {
	builder.PrependUint16Slot(1, id, 0)
}
func LatencyPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
