// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package events

import "strconv"

type Target int8

const (
	TargetPublisher  Target = 0
	TargetSubscriber Target = 1
)

var EnumNamesTarget = map[Target]string{
	TargetPublisher:  "Publisher",
	TargetSubscriber: "Subscriber",
}

var EnumValuesTarget = map[string]Target{
	"Publisher":  TargetPublisher,
	"Subscriber": TargetSubscriber,
}

func (v Target) String() string {
	if s, ok := EnumNamesTarget[v]; ok {
		return s
	}
	return "Target(" + strconv.FormatInt(int64(v), 10) + ")"
}
