"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.Target = void 0;
var Target;
(function (Target) {
    Target[Target["Publisher"] = 0] = "Publisher";
    Target[Target["Subscriber"] = 1] = "Subscriber";
})(Target = exports.Target || (exports.Target = {}));
