"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.Type = void 0;
var Type;
(function (Type) {
    Type[Type["Offer"] = 0] = "Offer";
    Type[Type["Answer"] = 1] = "Answer";
    Type[Type["Signal"] = 2] = "Signal";
    Type[Type["Join"] = 3] = "Join";
    Type[Type["Latency"] = 4] = "Latency";
})(Type = exports.Type || (exports.Type = {}));
